export const routerConfig = [
  {
    title: "基础工具",
    path: "/baseUtil",
    m_id: 1,
    parent_m_id: null,
    icon: "icon_list",
    keep_alive: "false",
    order: 1,
    children: [
      {
        title: "时间工具",
        path: "/timeUtil",
        m_id: 11,
        parent_m_id: 1,
        icon: null,
        keep_alive: "false",
        order: 5485,
      },
      {
        title: "文本处理",
        path: "/textUtil",
        m_id: 12,
        parent_m_id: 1,
        icon: null,
        keep_alive: "false",
        order: 9588,
      },
      {
        title: "数学工具",
        path: "/mathUtil",
        m_id: 13,
        parent_m_id: 1,
        icon: null,
        keep_alive: "false",
        order: 9588,
      },
      {
        title: "加密工具",
        path: "/cryptologyUtil",
        m_id: 14,
        parent_m_id: 1,
        icon: null,
        keep_alive: "false",
        order: 9588,
      },
      {
        title: "语言工具",
        path: "/langUtil",
        m_id: 15,
        parent_m_id: 1,
        icon: null,
        keep_alive: "false",
        order: 9588,
      },
    ],
  },
  {
    title: "文件工具",
    path: "/fileUtil",
    m_id: 4,
    parent_m_id: null,
    icon: "icon_voiceprint",
    keep_alive: "false",
    order: 4,
    children: [
      {
        title: "文件格式转换",
        path: "/conversion",
        m_id: 41,
        parent_m_id: 4,
        keep_alive: "false",
        order: 1,
      },
      {
        title: "文件加密",
        path: "/encryption",
        m_id: 42,
        parent_m_id: 4,
        keep_alive: "false",
        order: 2,
      }
    ],
  },
  {
    title: "专业工具",
    path: "/professionalUtil",
    m_id: 6,
    parent_m_id: null,
    icon: "icon_list",
    keep_alive: "false",
    order: 3,
    children: [
      {
        title: "颜色工具",
        path: "/colorUtil",
        m_id: 61,
        parent_m_id: 6,
        icon: null,
        keep_alive: "false",
        order: 1,
      },
      {
        title: "二维码工具",
        path: "/qrcodeUtil",
        m_id: 62,
        parent_m_id: 6,
        icon: null,
        keep_alive: "false",
        order: 2,
      }
    ],
  },
  {
    title: "关于",
    path: "/about",
    m_id: 5,
    parent_m_id: null,
    icon: "icon_MTR",
    keep_alive: "false",
    order: 5,
    children: [
      {
        title: "概述页",
        path: "/overview",
        m_id: 51,
        parent_m_id: 5,
        icon: "icon_addresslist",
        keep_alive: "false",
        order: 1,
      },
      {
        title: "其他作品",
        path: "/other",
        m_id: 52,
        parent_m_id: 5,
        icon: "icon_addresslist",
        keep_alive: "false",
        order: 2,
      },
    ],
  }

];
