export const routerConfig = [
  {
    title: "基础工具",
    path: "/baseUtil",
    m_id: 1,
    parent_m_id: null,
    icon: "icon_list",
    keep_alive: "false",
    order: 1,
    children: [
      {
        title: "时间工具",
        path: "/timeUtil",
        m_id: 11,
        parent_m_id: 1,
        icon: null,
        keep_alive: "false",
        order: 5485,
      },
      {
        title: "文本处理",
        path: "/textUtil",
        m_id: 12,
        parent_m_id: 1,
        icon: null,
        keep_alive: "false",
        order: 9588,
      },
      {
        title: "数学工具",
        path: "/mathUtil",
        m_id: 13,
        parent_m_id: 1,
        icon: null,
        keep_alive: "false",
        order: 9588,
      },
      {
        title: "加密工具",
        path: "/cryptologyUtil",
        m_id: 14,
        parent_m_id: 1,
        icon: null,
        keep_alive: "false",
        order: 9588,
      },
      {
        title: "语言工具",
        path: "/mathUtil",
        m_id: 15,
        parent_m_id: 1,
        icon: null,
        keep_alive: "false",
        order: 9588,
      },
    ],
  },
  {
    title: "表单页",
    path: "/form",
    m_id: 2,
    parent_m_id: null,
    icon: "icon_form",
    keep_alive: "false",
    order: 3,
    children: [
      {
        title: "基础表单",
        path: "/index",
        m_id: 21,
        parent_m_id: 2,
        icon: null,
        keep_alive: "false",
        order: 9654,
      },
    ],
  },
  {
    title: "文件处理",
    path: "/details",
    m_id: 3,
    parent_m_id: null,
    icon: "icon_edit",
    keep_alive: "false",
    order: 3,
    children: [
      {
        title: "个人中心",
        path: "/person",
        m_id: 31,
        parent_m_id: 3,
        icon: "icon_infopersonal",
        keep_alive: "false",
        order: 9998,
      },
    ],
  },
  {
    title: "结果页",
    path: "/result",
    m_id: 4,
    parent_m_id: null,
    icon: "icon_voiceprint",
    keep_alive: "false",
    order: 4,
    children: [
      {
        title: "403",
        path: "/403",
        m_id: 41,
        parent_m_id: 4,
        icon: "icon_locking",
        keep_alive: "false",
        order: 0,
      },
      {
        title: "404",
        path: "/404",
        m_id: 42,
        parent_m_id: 4,
        icon: "icon_close",
        keep_alive: "false",
        order: 1,
      },
      {
        title: "500",
        path: "/500",
        m_id: 43,
        parent_m_id: 4,
        icon: "icon_privacy_closed",
        keep_alive: "false",
        order: 4568,
      },
    ],
  },
  {
    title: "统计",
    path: "/statistics",
    m_id: 5,
    parent_m_id: null,
    icon: "icon_MTR",
    keep_alive: "true",
    order: 5,
    children: [
      {
        title: "访客统计",
        path: "/visitor",
        m_id: 51,
        parent_m_id: 5,
        icon: "icon_addresslist",
        keep_alive: "true",
        order: 1,
      },
    ],
  },
  {
    title: "系统管理",
    path: "/power",
    m_id: 6,
    parent_m_id: null,
    icon: "icon_set",
    keep_alive: "false",
    order: 9,
    children: [
      {
        title: "权限类别",
        path: "/type",
        m_id: 61,
        parent_m_id: 6,
        icon: "icon_safety",
        keep_alive: "true",
        order: 12,
      },
      {
        title: "菜单管理",
        path: "/menu",
        m_id: 62,
        parent_m_id: 6,
        icon: "icon_menu",
        keep_alive: "true",
        order: 1475,
      },
      {
        title: "用户管理",
        path: "/user",
        m_id: 63,
        parent_m_id: 6,
        icon: "icon_infopersonal",
        keep_alive: "true",
        order: 1593,
      },
    ],
  },
  {
    title: "图标库",
    path: "/icons",
    m_id: 7,
    parent_m_id: null,
    icon: "icon_pen",
    keep_alive: "true",
    order: 10,
  },
];
